-- Đề 01

-- 1.1

CREATE DATABASE QlyPhongKham

USE QlyPhongKham

CREATE TABLE PHONGKHAM (
	MAPH CHAR(4) PRIMARY KEY,
	TENPH VARCHAR(50),
	DIACHI VARCHAR(50)
)

CREATE TABLE NHACUNGCAP (
	MANCC CHAR(4) PRIMARY KEY,
	TENNCC VARCHAR(50),
	DIACHI VARCHAR(50),
)

CREATE TABLE THUOC (
	MATHUOC CHAR(4) PRIMARY KEY,
	TENTHUOC VARCHAR(20),
	DVT VARCHAR(5),
	GIATHUOC MONEY,
	MANCC CHAR(4) FOREIGN KEY REFERENCES NHACUNGCAP(MANCC)
)

CREATE TABLE BENHNHAN (
	MABN CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(50),
	SDT VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH CHAR(3)
)

CREATE TABLE KHAMBENH (
	MAKB CHAR(10) PRIMARY KEY,
	MAPH CHAR(4) FOREIGN KEY REFERENCES PHONGKHAM(MAPH),
	MABN CHAR(4) FOREIGN KEY REFERENCES BENHNHAN(MABN),
	NGKHAM SMALLDATETIME,
	CHANDOAN VARCHAR(50),
	GHICHU VARCHAR(100)
)

CREATE TABLE DONTHUOC (
	MAKB CHAR(10) FOREIGN KEY REFERENCES KHAMBENH(MAKB),
	MATHUOC CHAR(4) FOREIGN KEY REFERENCES THUOC(MATHUOC),
	SL INT,
	THANHTIEN MONEY,
	PRIMARY KEY (MAKB, MATHUOC)
)

-- 1.2

ALTER TABLE NHACUNGCAP ADD GHICHU VARCHAR(50)

-- 1.3

INSERT INTO NHACUNGCAP VALUES
('NCC1', 'NHACUNGCAP1', 'BINHDUONG', 'RONG'),
('NCC2', 'NHACUNGCAP2', 'BINHDUONG', 'RONG')

INSERT INTO THUOC VALUES
('TH01', 'THUOC1', 'VIEN', 10000, 'NCC1'),
('TH02', 'THUOC2', 'VIEN', 20000, 'NCC2')

-- 2.1

ALTER TABLE THUOC ADD CONSTRAINT CK_GIA CHECK (GIATHUOC > 0)

-- 2.2

ALTER TABLE THUOC ADD CONSTRAINT CK_DVT CHECK (DVT IN ('chai', 'hop', 'vien'))

-- 2.3

GO
CREATE TRIGGER INSERT_UPDATE_DONTHUOC
ON DONTHUOC
AFTER INSERT, UPDATE
AS
BEGIN
	IF NOT UPDATE(SL)
		RETURN
	BEGIN
		UPDATE DT
        SET DT.THANHTIEN = I.SL * T.GIATHUOC
        FROM DONTHUOC DT
        JOIN INSERTED I ON DT.MAKB = I.MAKB AND DT.MATHUOC = I.MATHUOC
        JOIN THUOC T ON T.MATHUOC = I.MATHUOC
	END
END

-- 3.1

SELECT T.MATHUOC, T.TENTHUOC, NCC.TENNCC
FROM THUOC T
JOIN NHACUNGCAP NCC ON NCC.MANCC = T.MANCC
ORDER BY T.GIATHUOC ASC

-- 3.2

SELECT P.MAPH, SUM(DT.THANHTIEN) AS TONGDOANHTHU
FROM PHONGKHAM P
JOIN KHAMBENH KB ON KB.MAPH = P.MAPH
JOIN DONTHUOC DT ON DT.MAKB = KB.MAKB
WHERE YEAR(KB.NGKHAM) = 2017
GROUP BY P.MAPH, MONTH(KB.NGKHAM)

-- 3.3

SELECT NCC.MANCC, NCC.TENNCC
FROM NHACUNGCAP NCC
JOIN THUOC T ON T.MANCC = NCC.MANCC
WHERE T.GIATHUOC > 30000
EXCEPT
SELECT NCC.MANCC, NCC.TENNCC
FROM NHACUNGCAP NCC
JOIN THUOC T ON T.MANCC = NCC.MANCC
WHERE T.GIATHUOC <= 30000

-- 3.4

WITH THONGKE AS (SELECT BN.MABN, BN.HOTEN, COUNT(KB.MAKB) AS SOLANKHAMBENH
	FROM BENHNHAN BN
	JOIN KHAMBENH KB ON KB.MABN = BN.MABN
	WHERE YEAR(KB.NGKHAM) = 2017)
SELECT TOP 1 WITH TIES TK.MABN, TK.HOTEN
FROM THONGKE TK
ORDER BY SOLANKHAMBENH DESC

-- 3.5

SELECT BN.MABN, BN.HOTEN
FROM BENHNHAN BN
JOIN KHAMBENH KB ON KB.MABN = BN.MABN
WHERE KB.NGKHAM = '2017-1-1'
AND KB.MAPH = 'pk1'
INTERSECT
SELECT BN.MABN, BN.HOTEN
FROM BENHNHAN BN
JOIN KHAMBENH KB ON KB.MABN = BN.MABN
WHERE KB.NGKHAM = '2017-1-1'
AND KB.MAPH = 'pk2'

-- 3.6

SELECT P.MAPH, P.TENPH
FROM PHONGKHAM P
JOIN KHAMBENH KB ON KB.MAPH = P.MAPH
JOIN BENHNHAN BN ON BN.MABN = KB.MABN
WHERE BN.GIOITINH = 'Nu'
AND YEAR(BN.NGSINH) = 1960
GROUP BY P.MAPH, P.TENPH
HAVING COUNT(DISTINCT KB.MABN) = (SELECT COUNT(*) 
	FROM BENHNHAN
	WHERE YEAR(NGSINH) = 1960
	AND GIOITINH = 'Nu')

-- Đề 02

-- 1.1

CREATE DATABASE QlyBenhVien

USE QlyBenhVien

CREATE TABLE BENHVIEN (
	MABV CHAR(4) PRIMARY KEY,
	TENBV VARCHAR(50),
	DIACHI VARCHAR(50)
)

CREATE TABLE NHASX (
	MANSX CHAR(4) PRIMARY KEY,
	TENNSX VARCHAR(50),
	DIACHI VARCHAR(50)
)

CREATE TABLE THUOC (
	MATHUOC CHAR(4) PRIMARY KEY,
	TENTHUOC VARCHAR(20),
	DVT VARCHAR(5),
	GIATHUOC MONEY,
	MANSX CHAR(4) FOREIGN KEY REFERENCES NHASX(MANSX)
)

CREATE TABLE BENHNHAN (
	MABN CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(50),
	SDT VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH CHAR(3)
)

CREATE TABLE KHAMBENH (
	MAKB CHAR(10) PRIMARY KEY,
	MABV CHAR(4) FOREIGN KEY REFERENCES BENHVIEN(MABV),
	MABN CHAR(4) FOREIGN KEY REFERENCES BENHNHAN(MABN),
	NGKHAM SMALLDATETIME,
	CHANDOAN VARCHAR(50),
	GHICHU VARCHAR(100)
)

CREATE TABLE TOATHUOC (
	MAKB CHAR(10) FOREIGN KEY REFERENCES KHAMBENH(MAKB),
	MATHUOC CHAR(4) FOREIGN KEY REFERENCES THUOC(MATHUOC),
	SL INT,
	TRIGIA MONEY
	PRIMARY KEY (MAKB, MATHUOC)
)

-- 1.2

ALTER TABLE NHASX ALTER COLUMN DIACHI VARCHAR(100)

-- 1.3

INSERT INTO BENHVIEN VALUES ('BV01', 'Benh vien Cho Ray', '201B Nguyen Chi Thanh TPHCM');

INSERT INTO BENHNHAN VALUES ('BN01', 'Nguyen Van A', '0901234567', '1990-01-01', 'Nam');

INSERT INTO KHAMBENH VALUES ('KB001', 'BV01', 'BN01', '2017-05-20', 'Sot xuat huyet', 'Can theo doi them');

-- 2.1

ALTER TABLE BENHNHAN ADD CONSTRAINT CK_GT CHECK (GIOITINH IN ('Nam', 'Nu'))

-- 2.2

ALTER TABLE TOATHUOC ADD CONSTRAINT CK_SL CHECK (SL > 0)

-- 2.3

GO
CREATE TRIGGER INSERT_UPDATE_TOATHUOC
ON TOATHUOC
AFTER INSERT, UPDATE
AS
BEGIN
	IF NOT UPDATE(SL)
		RETURN
	BEGIN
		UPDATE TT
		SET TT.TRIGIA = I.SL * T.GIATHUOC
		FROM TOATHUOC TT
		JOIN INSERTED I ON I.MAKB = TT.MAKB AND I.MATHUOC = TT.MATHUOC
		JOIN THUOC T ON T.MATHUOC = I.MATHUOC
	END
END

-- 3.1

SELECT T.MATHUOC, T.TENTHUOC, NSX.TENNSX
FROM THUOC T
JOIN NHASX NSX ON NSX.MANSX = T.MANSX
ORDER BY T.GIATHUOC DESC

-- 3.2

SELECT BN.MABN, BN.HOTEN, COUNT(KB.MAKB) AS SOLANKHAMBENH
FROM BENHNHAN BN 
JOIN KHAMBENH KB ON KB.MABN = BN.MABN
WHERE YEAR(KB.NGKHAM) = 2016
GROUP BY BN.MABN, BN.HOTEN, MONTH(KB.NGKHAM)

-- 3.3

SELECT NSX.MANSX, NSX.TENNSX
FROM NHASX NSX
JOIN THUOC T ON T.MANSX = NSX.MANSX
WHERE T.GIATHUOC <= 59000
EXCEPT
SELECT NSX.MANSX, NSX.TENNSX
FROM NHASX NSX
JOIN THUOC T ON T.MANSX = NSX.MANSX
WHERE T.GIATHUOC > 59000

-- 3.4

WITH THONGKE AS (SELECT BV.MABV, BV.TENBV, COUNT(KB.MABN) AS SLBENHNHAN
	FROM BENHVIEN BV
	JOIN KHAMBENH KB ON KB.MABV = BV.MABV
	WHERE YEAR(KB.NGKHAM) = 2017
	GROUP BY BV.MABV, BV.TENBV)
SELECT TOP 1 WITH TIES TK.MABV, TK.TENBV
FROM THONGKE TK
ORDER BY SLBENHNHAN DESC

-- 3.5

SELECT BN.MABN, BN.HOTEN
FROM BENHNHAN BN
JOIN KHAMBENH KB ON KB.MABN = BN.MABN
WHERE KB.MABV = 'bv1'
AND YEAR(KB.NGKHAM) = 2017
EXCEPT
SELECT BN.MABN, BN.HOTEN
FROM BENHNHAN BN
JOIN KHAMBENH KB ON KB.MABN = BN.MABN
WHERE KB.MABV = 'bv2'
AND YEAR(KB.NGKHAM) = 2017

-- 3.6

SELECT BV.MABV, BV.TENBV
FROM BENHVIEN BV
JOIN KHAMBENH KB ON KB.MABV = BV.MABV
JOIN BENHNHAN BN ON BN.MABN = KB.MABN
WHERE BN.GIOITINH = 'Nam'
AND YEAR(BN.NGSINH) < 1980
GROUP BY BV.MABV, BV.TENBV
HAVING COUNT(DISTINCT KB.MABN) = (SELECT COUNT(*)
	FROM BENHNHAN
	WHERE GIOITINH = 'Nam'
	AND YEAR(NGSINH) < 1980)