-- Câu 1

CREATE DATABASE QlySinhVien

USE QlySinhVien

CREATE TABLE SINHVIEN (
	MASV VARCHAR(10) PRIMARY KEY,
	HOTEN VARCHAR(50),
	NAMSINH SMALLINT,
	MALOP VARCHAR(10)
)

CREATE TABLE KHOA (
	MAKHOA VARCHAR(10) PRIMARY KEY,
	TENKHOA VARCHAR(50)
)

CREATE TABLE MON (
	MAMH VARCHAR(10) PRIMARY KEY,
	TENMH VARCHAR(50),
	SOTC TINYINT,
	MAKHOA VARCHAR(10) FOREIGN KEY REFERENCES KHOA(MAKHOA)
)

CREATE TABLE DANGKY (
	MASV VARCHAR(10) FOREIGN KEY REFERENCES SINHVIEN(MASV),
	MAMH VARCHAR(10) FOREIGN KEY REFERENCES MON(MAMH),
	HOCKY TINYINT,
	NAMHOC SMALLINT,
	PRIMARY KEY (MASV, MAMH)
)

-- Câu 2

-- a

ALTER TABLE MON ADD CONSTRAINT CK_SOTC CHECK (SOTC BETWEEN 2 AND 4)

-- b

GO
CREATE TRIGGER INSERT_UPDATE_DANGKY
ON DANGKY
AFTER INSERT, UPDATE
AS
BEGIN
	IF UPDATE(NAMHOC) OR UPDATE(MASV)
	BEGIN
		IF EXISTS (SELECT 1
			FROM INSERTED I
			JOIN SINHVIEN SV ON I.MASV = SV.MASV
			WHERE SV.NAMSINH >= I.NAMHOC)
		BEGIN
			ROLLBACK TRANSACTION
			PRINT ('LOI')
		END
	END
END

GO
CREATE TRIGGER UPDATE_SINHVIEN
ON SINHVIEN
AFTER UPDATE
AS
BEGIN
	IF UPDATE(NAMSINH)
	BEGIN
		IF EXISTS (SELECT 1
			FROM INSERTED I
			JOIN DANGKY DK ON I.MASV = DK.MASV
			WHERE I.NAMSINH >= DK.NAMHOC)
		BEGIN
			ROLLBACK TRANSACTION
			PRINT ('LOI')
		END
	END
END

-- Câu 3

-- a

SELECT *
FROM SINHVIEN 
WHERE MALOP = 'HTCL2022' 
ORDER BY HOTEN ASC

-- b

SELECT SV.MASV, SV.HOTEN, COUNT(DK.MAMH)
FROM SINHVIEN SV
JOIN DANGKY DK ON DK.MASV = SV.MASV
WHERE DK.HOCKY = 1
AND DK.NAMHOC = 2023
GROUP BY SV.MASV, SV.HOTEN

-- c

SELECT SV.MASV, SV.HOTEN
FROM SINHVIEN SV
JOIN DANGKY DK ON DK.MASV = SV.MASV
WHERE SV.MALOP = 'HTCL2021'
AND DK.NAMHOC = 2023
EXCEPT
SELECT SV.MASV, SV.HOTEN
FROM SINHVIEN SV
JOIN DANGKY DK ON DK.MASV = SV.MASV
JOIN MON M ON M.MAMH = DK.MAMH
WHERE  M.TENMH = 'He quan tri Co so du lieu'
AND DK.NAMHOC = 2023
AND SV.MALOP = 'HTCL2021'

-- d

SELECT SV.HOTEN
FROM SINHVIEN SV
JOIN DANGKY DK ON DK.MASV = SV.MASV
JOIN MON M ON M.MAMH = DK.MAMH
WHERE SV.MALOP = 'HTCL2021'
AND DK.NAMHOC = 2023
AND DK.HOCKY = 2
AND M.TENMH = 'He quan tri Co so du lieu'
INTERSECT
SELECT SV.HOTEN
FROM SINHVIEN SV
JOIN DANGKY DK ON DK.MASV = SV.MASV
JOIN MON M ON M.MAMH = DK.MAMH
WHERE SV.MALOP = 'HTCL2021'
AND DK.NAMHOC = 2023
AND DK.HOCKY = 2
AND M.TENMH = 'Lap trinh Java'

-- e

SELECT SV.HOTEN
FROM SINHVIEN SV
JOIN DANGKY DK ON DK.MASV = SV.MASV
JOIN MON M ON M.MAMH = DK.MAMH
JOIN KHOA K ON K.MAKHOA = M.MAKHOA
WHERE K.TENKHOA = 'He thong thong tin'
GROUP BY SV.MASV, SV.HOTEN
HAVING COUNT(DISTINCT DK.MAMH) = (SELECT COUNT(*)
	FROM MON 
	JOIN KHOA ON KHOA.MAKHOA = MON.MAKHOA
	WHERE TENKHOA = 'He thong thong tin')

-- f

WITH THONGKE AS (SELECT M.MAMH, M.TENMH, COUNT(DK.MASV) AS SOLUONGDK
	FROM MON M
	JOIN DANGKY DK ON DK.MAMH = M.MAMH
	WHERE DK.HOCKY = 1
	AND DK.NAMHOC = 2023
	GROUP BY M.MAMH, M.TENMH)
SELECT TOP 1 WITH TIES TK.MAMH, TK.TENMH
FROM THONGKE TK
ORDER BY SOLUONGDK DESC