-- Câu 1

CREATE DATABASE QlyCaSi

USE QlyCaSi

CREATE TABLE CASI (
	MACS CHAR(5) PRIMARY KEY,
	HOTEN VARCHAR(30),
	NGAYSINH SMALLDATETIME,
	SODT VARCHAR(15)
)

CREATE TABLE TACGIA (
	MATG CHAR(5) PRIMARY KEY,
	HOTEN VARCHAR(20),
	NGSINH SMALLDATETIME,
	SODT INT
)

CREATE TABLE BAIHAT (
	MABH CHAR(5) PRIMARY KEY,
	TENBH VARCHAR(25),
	NGAYST SMALLDATETIME,
	MATG CHAR(5) FOREIGN KEY REFERENCES TACGIA(MATG)
)

CREATE TABLE LICHDIEN (
	MACS CHAR(5) FOREIGN KEY REFERENCES CASI(MACS),
	MABH CHAR(5) FOREIGN KEY REFERENCES BAIHAT(MABH),
	NGAYDIEN SMALLDATETIME,
	DIADIEM VARCHAR(50),
	TENSK VARCHAR(20)
	PRIMARY KEY (MACS, MABH, NGAYDIEN)
)

-- Câu 2

-- a

GO
CREATE TRIGGER TRG_LICHDIEN
ON LICHDIEN
AFTER UPDATE, DELETE
AS
BEGIN
	IF EXISTS (SELECT 1 
		FROM LICHDIEN 
		GROUP BY MACS, NGAYDIEN
		HAVING COUNT(MABH) < 2)
	BEGIN
		ROLLBACK TRANSACTION
		PRINT ('LOI')
	END
END

-- b

GO
CREATE TRIGGER INSERT_UPDATE_LICHDIEN
ON LICHDIEN
AFTER INSERT, UPDATE
AS 
BEGIN
	IF UPDATE(NGAYDIEN) OR UPDATE(MACS)
	BEGIN
		IF EXISTS (SELECT 1 
			FROM INSERTED I
			JOIN CASI CS ON CS.MACS = I.MACS
			WHERE CS.NGAYSINH >= I.NGAYDIEN)
		BEGIN
			ROLLBACK TRANSACTION
			PRINT ('LOI')
		END
	END
END

GO
CREATE TRIGGER UPDATE_CASI
ON CASI
AFTER UPDATE
AS 
BEGIN
	IF UPDATE(NGAYSINH)
	BEGIN
		IF EXISTS (SELECT 1 
			FROM INSERTED I
			JOIN LICHDIEN LD ON LD.MACS = I.MACS
			WHERE I.NGAYSINH >= LD.NGAYDIEN)
		BEGIN
			ROLLBACK TRANSACTION
			PRINT ('LOI')
		END
	END
END

-- Câu 3

-- a

SELECT BH.MABH, BH.TENBH
FROM BAIHAT BH
JOIN TACGIA TG ON TG.MATG = BH.MATG
JOIN LICHDIEN LD ON LD.MABH = BH.MABH
WHERE TG.HOTEN = 'Trinh Cong Son'
AND LD.NGAYDIEN = '2021-09-26'
ORDER BY BH.TENBH ASC

-- b

SELECT TG.MATG, TG.HOTEN
FROM BAIHAT BH
JOIN TACGIA TG ON TG.MATG = BH.MATG
JOIN LICHDIEN LD ON LD.MABH = BH.MABH
JOIN CASI CS ON CS.MACS = LD.MACS
WHERE BH.TENBH = 'Noi vong tay lon'
AND CS.HOTEN = 'Ta Minh Tam'
AND LD.NGAYDIEN = '2021-09-26'

-- c

SELECT CS.MACS, CS.HOTEN, COUNT(LD.MABH) AS SOLUONGBAIHAT
FROM CASI CS
JOIN LICHDIEN LD ON LD.MACS = CS.MACS
WHERE LD.NGAYDIEN = '2021-09-26'
GROUP BY CS.MACS, CS.HOTEN

-- d

SELECT CS.HOTEN
FROM CASI CS 
JOIN LICHDIEN LD ON CS.MACS = LD.MACS
JOIN BAIHAT BH ON BH.MABH = LD.MABH
JOIN TACGIA TG ON TG.MATG = BH.MATG
WHERE LD.NGAYDIEN = '2023-12-22'
AND LD.TENSK = 'san van dong My Dinh Ha Noi'
AND TG.HOTEN = 'Van Cao'
EXCEPT
SELECT CS.HOTEN
FROM CASI CS 
JOIN LICHDIEN LD ON CS.MACS = LD.MACS
JOIN BAIHAT BH ON BH.MABH = LD.MABH
JOIN TACGIA TG ON TG.MATG = BH.MATG
WHERE LD.NGAYDIEN = '2023-12-22'
AND LD.TENSK = 'san van dong My Dinh Ha Noi'
AND TG.HOTEN = 'Hoang Quy'

-- e

SELECT CS.HOTEN
FROM CASI CS
JOIN LICHDIEN LD ON CS.MACS = LD.MACS
JOIN BAIHAT BH ON BH.MABH = LD.MABH
JOIN TACGIA TG ON TG.MATG = BH.MATG
WHERE TG.HOTEN = 'Trinh Cong Son'
AND YEAR(BH.NGAYST) > 1990
GROUP BY CS.MACS, CS.HOTEN
HAVING COUNT(DISTINCT LD.MABH) = (SELECT COUNT(*)
	FROM BAIHAT 
	JOIN TACGIA ON BAIHAT.MATG = TACGIA.MATG
	WHERE HOTEN = 'Trinh Cong Son'
	AND YEAR(NGAYST) > 1990)

-- f

WITH THONGKE AS (SELECT CS.MACS, CS.HOTEN, COUNT(LD.MABH) AS SOLUONGBH
	FROM CASI CS
	JOIN LICHDIEN LD ON CS.MACS = LD.MACS
	JOIN BAIHAT BH ON BH.MABH = LD.MABH
	JOIN TACGIA TG ON TG.MATG = BH.MATG
	WHERE TG.HOTEN = 'Trinh Cong Son'
	GROUP BY CS.MACS, CS.HOTEN)
SELECT TOP 1 WITH TIES TK.MACS, TK.HOTEN
FROM THONGKE TK
ORDER BY SOLUONGBH DESC