-- Câu 1

-- 1.1

CREATE DATABASE QlyLaiXe

USE QlyLaiXe

CREATE TABLE XEPLOAI (
	MAXEPLOAI CHAR(4) PRIMARY KEY,
	TENXEPLOAI VARCHAR(20)
)

CREATE TABLE HOCVIEN (
	MAHV CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(30),
	NGSINH SMALLDATETIME,
	DIACHI VARCHAR(30),
	EMAIL VARCHAR(30),
	SDT VARCHAR(15),
	MAXEPLOAI CHAR(4) FOREIGN KEY REFERENCES XEPLOAI(MAXEPLOAI)
)

CREATE TABLE GIAOVIEN (
	MAGV CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(30),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
)

CREATE TABLE XE (
	MAXE CHAR(4) PRIMARY KEY,
	BIENSO VARCHAR(10),
	TENLOAIXE VARCHAR(20)
)

CREATE TABLE BAIHOC (
	MABAIHOC CHAR(4) PRIMARY KEY,
	NGAYHOC SMALLDATETIME,
	SOGIO INT,
	GIA MONEY,
	MAHV CHAR(4) FOREIGN KEY REFERENCES HOCVIEN(MAHV),
	MAGV CHAR(4) FOREIGN KEY REFERENCES GIAOVIEN(MAGV),
	MAXE CHAR(4) FOREIGN KEY REFERENCES XE(MAXE)
)

-- 1.2

INSERT INTO XEPLOAI VALUES ('XL01', 'gioi')

INSERT INTO HOCVIEN VALUES ('HV01', 'Duy Hung', '2006-11-01', 'Binh Duong', '24520602@gm.uit.edu.vn', '0123456789', 'XL01')

INSERT INTO GIAOVIEN VALUES ('GV01', 'Bich Huyen', '2006-12-27', '2025-12-27')

INSERT INTO XE VALUES ('X001', '18-AB12345', 'Xe SH')

INSERT INTO BAIHOC VALUES ('BH01', '2025-7-1', 36, 1800000, 'HV01', 'GV01', 'X001')

-- 1.3 

UPDATE HOCVIEN SET HOTEN = 'Nguyen Duy Hung' WHERE HOTEN = 'Duy Hung'

-- Câu 2

-- 2.1

ALTER TABLE XEPLOAI ADD CONSTRAINT CHECK_TENXEPLOAI CHECK (TENXEPLOAI IN ('gioi', 'kha', 'trung binh', 'kem'))

-- 2.2

ALTER TABLE BAIHOC ADD CONSTRAINT CHECK_GIABAIHOC CHECK (GIA > 0)

-- 2.3

GO
CREATE TRIGGER INSERT_BAIHOC
ON BAIHOC
AFTER INSERT
AS
BEGIN
	IF EXISTS (SELECT 1 
		FROM INSERTED I 
		JOIN HOCVIEN HV ON HV.MAHV = I.MAHV
		WHERE HV.NGSINH >= I.NGAYHOC)
	BEGIN
		ROLLBACK TRANSACTION
		PRINT ('LOI')
	END
END

-- Câu 3

-- 3.1

SELECT HV.MAHV, HV.HOTEN
FROM HOCVIEN HV
JOIN XEPLOAI XL ON XL.MAXEPLOAI = HV.MAXEPLOAI
WHERE XL.TENXEPLOAI = 'gioi'

-- 3.2

SELECT MABAIHOC, NGAYHOC, SOGIO
FROM BAIHOC
WHERE GIA = (SELECT MAX(GIA) FROM BAIHOC)

-- 3.3

SELECT HV.MAHV, HV.HOTEN
FROM HOCVIEN HV
JOIN BAIHOC BH ON BH.MAHV = HV.MAHV
WHERE BH.NGAYHOC = '2018-5-5'
INTERSECT
SELECT HV.MAHV, HV.HOTEN
FROM HOCVIEN HV
JOIN BAIHOC BH ON BH.MAHV = HV.MAHV
WHERE BH.NGAYHOC = '2018-5-6'

-- 3.4

SELECT X.MAXE, X.BIENSO
FROM XE X
JOIN BAIHOC BH ON BH.MAXE = X.MAXE
WHERE BH.NGAYHOC = '2018-1-1'
EXCEPT
SELECT X.MAXE, X.BIENSO
FROM XE X
JOIN BAIHOC BH ON BH.MAXE = X.MAXE
WHERE BH.NGAYHOC = '2018-1-2'

-- 3.5

WITH THONGKE AS (SELECT X.MAXE, X.BIENSO, COUNT(BH.MABAIHOC) AS SOLUONGBH 
	FROM XE X 
	JOIN BAIHOC BH ON BH.MAXE = X.MAXE
	WHERE MONTH(BH.NGAYHOC) = 8 
	AND YEAR(BH.NGAYHOC) = 2018
	GROUP BY X.MAXE, X.BIENSO)
SELECT TK.MAXE, TK.BIENSO
FROM THONGKE TK
WHERE SOLUONGBH > 100

-- 3.6

SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
JOIN BAIHOC BH ON BH.MAGV = GV.MAGV
JOIN XE X ON X.MAXE = BH.MAXE
WHERE YEAR(BH.NGAYHOC) = 2017
AND X.TENLOAIXE = 'Ford'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT X.MAXE) = (SELECT COUNT(*) 
	FROM XE 
	WHERE TENLOAIXE = 'Ford')

-- 3.7

SELECT HV.MAHV, HV.HOTEN, SUM(BH.SOGIO) AS TONGSOGIO
FROM HOCVIEN HV
JOIN BAIHOC BH ON BH.MAHV = HV.MAHV
WHERE YEAR(BH.NGAYHOC) = 2016
GROUP BY HV.MAHV, HV.HOTEN